# This files if intended to be uploaded to Digit. 
# And it does not include any other config changes.

[lowlevelapi]
enable = true
# Time in seconds between Low-level API packets before control program
# disables robot
timeout = 0.05
# Port for incoming and outgoing Low-level API communications.
# Change if these settings interfere with any other programs or network
# Traffic on the payload computer. Must match settings in lowlevelapi.c
# (lines 181 and 183). These should not be changed under normal operation
listen-port = 25500
send-port = 25501

[logging]
enable-cyclic-logs = true
enable-event-log = true
enable-summary-log = true
enable-visualizer-log = true
log-directory = "/tmp/control"
summary-log-directory = "/tmp/summary"
