channels:
  - conda-forge
dependencies:
  - dash=2.18.0
  - ffmpeg=7.0.2
  - imageio=2.35.1
  - matplotlib=3.9.2
  - numpy=2.1.1
  - pandas=2.2.2
  - pip=24.2
  - plotly=5.24.0
  - python=3.10.14
  - pytorch=2.4.0
  - scipy=1.14.1
  - pip:
    - ./sim/digit_sim/digit_ar_sim/agility-1.1.1-py3-none-any.whl
    - agility==1.1.1
    - dash-bootstrap-components==1.6.0
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - glfw==2.7.0
    - inputs==0.5
    - matplotlib-inline==0.1.7
    - mediapy==1.2.2
    - mujoco==3.2.2
    - opencv-python==4.10.0.84
    - pathtools==0.1.2
    - perlin-noise==1.13
    - psutil==6.0.0
    - ray==2.35.0
    - tensorboard==2.17.1
    - tensorboard-data-server==0.7.2
    - wandb==0.17.9
