n_traj: 100
benchmarks:
- idx: 0
  name: commandability for 1 cassie in rectangle at x=0, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 1
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 0
    h: 0.75
- idx: 1
  name: commandability for 1 cassie in rectangle at x=1, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 1
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 1
    y: 0
    t: 0
    h: 0.75
- idx: 2
  name: commandability for 1 cassie in rectangle at x=0, y=0.25, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 1
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0.25
    t: 0
    h: 0.75
- idx: 3
  name: commandability for 1 cassie in rectangle at x=0, y=0, t=15, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 1
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 15
    h: 0.75
- idx: 4
  name: commandability for 2 cassie in rectangle at x=0, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 2
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 0
    h: 0.75
- idx: 5
  name: commandability for 2 cassie in rectangle at x=1, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 2
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 1
    y: 0
    t: 0
    h: 0.75
- idx: 6
  name: commandability for 2 cassie in rectangle at x=0, y=0.25, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 2
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0.25
    t: 0
    h: 0.75
- idx: 7
  name: commandability for 2 cassie in rectangle at x=0, y=0, t=15, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 2
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 15
    h: 0.75
- idx: 8
  name: commandability for 3 cassie in rectangle at x=0, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 3
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 0
    h: 0.75
- idx: 9
  name: commandability for 3 cassie in rectangle at x=1, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 3
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 1
    y: 0
    t: 0
    h: 0.75
- idx: 10
  name: commandability for 3 cassie in rectangle at x=0, y=0.25, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 3
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0.25
    t: 0
    h: 0.75
- idx: 11
  name: commandability for 3 cassie in rectangle at x=0, y=0, t=15, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 3
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 15
    h: 0.75
- idx: 12
  name: commandability for 4 cassie in rectangle at x=0, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 4
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 0
    h: 0.75
- idx: 13
  name: commandability for 4 cassie in rectangle at x=1, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 4
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 1
    y: 0
    t: 0
    h: 0.75
- idx: 14
  name: commandability for 4 cassie in rectangle at x=0, y=0.25, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 4
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0.25
    t: 0
    h: 0.75
- idx: 15
  name: commandability for 4 cassie in rectangle at x=0, y=0, t=15, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 4
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 15
    h: 0.75
- idx: 16
  name: commandability for 5 cassie in rectangle at x=0, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 5
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 0
    h: 0.75
- idx: 17
  name: commandability for 5 cassie in rectangle at x=1, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 5
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 1
    y: 0
    t: 0
    h: 0.75
- idx: 18
  name: commandability for 5 cassie in rectangle at x=0, y=0.25, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 5
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0.25
    t: 0
    h: 0.75
- idx: 19
  name: commandability for 5 cassie in rectangle at x=0, y=0, t=15, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 5
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 15
    h: 0.75
- idx: 20
  name: commandability for 6 cassie in rectangle at x=0, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 6
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 0
    h: 0.75
- idx: 21
  name: commandability for 6 cassie in rectangle at x=1, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 6
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 1
    y: 0
    t: 0
    h: 0.75
- idx: 22
  name: commandability for 6 cassie in rectangle at x=0, y=0.25, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 6
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0.25
    t: 0
    h: 0.75
- idx: 23
  name: commandability for 6 cassie in rectangle at x=0, y=0, t=15, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 6
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 15
    h: 0.75
- idx: 24
  name: commandability for 7 cassie in rectangle at x=0, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 7
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 0
    h: 0.75
- idx: 25
  name: commandability for 7 cassie in rectangle at x=1, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 7
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 1
    y: 0
    t: 0
    h: 0.75
- idx: 26
  name: commandability for 7 cassie in rectangle at x=0, y=0.25, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 7
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0.25
    t: 0
    h: 0.75
- idx: 27
  name: commandability for 7 cassie in rectangle at x=0, y=0, t=15, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 7
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 15
    h: 0.75
- idx: 28
  name: commandability for 8 cassie in rectangle at x=0, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 8
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 0
    h: 0.75
- idx: 29
  name: commandability for 8 cassie in rectangle at x=1, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 8
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 1
    y: 0
    t: 0
    h: 0.75
- idx: 30
  name: commandability for 8 cassie in rectangle at x=0, y=0.25, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 8
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0.25
    t: 0
    h: 0.75
- idx: 31
  name: commandability for 8 cassie in rectangle at x=0, y=0, t=15, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 8
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 15
    h: 0.75
- idx: 32
  name: commandability for 9 cassie in rectangle at x=0, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 9
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 0
    h: 0.75
- idx: 33
  name: commandability for 9 cassie in rectangle at x=1, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 9
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 1
    y: 0
    t: 0
    h: 0.75
- idx: 34
  name: commandability for 9 cassie in rectangle at x=0, y=0.25, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 9
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0.25
    t: 0
    h: 0.75
- idx: 35
  name: commandability for 9 cassie in rectangle at x=0, y=0, t=15, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 9
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 15
    h: 0.75
- idx: 36
  name: commandability for 10 cassie in rectangle at x=0, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 10
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 0
    h: 0.75
- idx: 37
  name: commandability for 10 cassie in rectangle at x=1, y=0, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 10
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 1
    y: 0
    t: 0
    h: 0.75
- idx: 38
  name: commandability for 10 cassie in rectangle at x=0, y=0.25, t=0, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 10
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0.25
    t: 0
    h: 0.75
- idx: 39
  name: commandability for 10 cassie in rectangle at x=0, y=0, t=15, h=0.75, force=0,
    policy=trained_3_torque_joint_force_randomize_weight
  env:
    num_cassie: 10
    terrain: cassiepede_rectangle
    time_horizon: 1000
    policy: trained_3_torque_joint_force_randomize_weight
    checkpoint: latest
    run_name: '2024-05-20 19:05:06.757875'
    force: 0
  command:
    x: 0
    y: 0
    t: 15
    h: 0.75
